rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0-preview2
  - rbx
  - jruby

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby

# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

script:
  - bundle exec rspec
  - bundle exec rubocop -D
